### ISSUE TITLE
Lost AMF hwa

### ISSUE THREAD

**Issue by tedhinklater** [ErsatzTV/ErsatzTV#1518] opened 2023-12-02 11:38 UTC
I have an i3-9100F and AMD RX6600. With v0.8.2-beta I could run h264 format with AMF no problems but in v0.8.3-beta, AMF is removed, my only options were None, QSV or NVENC which aren't compatible with my setup. Had to revert and rebuild everything because I didn't notice the AppData/Local folders. 0.8.2 is working fine again. Is AMF completely gone from now on?

**Comment by jasongdove** [comment] 2023-12-02 14:42
I can't specifically tell without the full ETV version (found below the left menu), but I assume you're using Windows?

I had to make a custom build of ffmpeg for the latest release to workaround this NVIDIA regression https://trac.ffmpeg.org/ticket/10668

If AMF was indeed removed, that was accidental. Will investigate.

**Comment by jasongdove** [comment] 2023-12-02 14:52
This looks like a regression from https://github.com/ErsatzTV/ErsatzTV/pull/1471 - the AMF detection code isn't correct; ffmpeg still has the right encoders.

Will fix.

**Comment by jasongdove** [comment] 2023-12-02 15:14
@tedhinklater  This should be fixed with https://github.com/ErsatzTV/ErsatzTV/pull/1519

Please test using the latest develop build found at https://github.com/ErsatzTV/ErsatzTV/releases/tag/develop

**Comment by tedhinklater** [comment] 2023-12-02 22:35
Thanks for the super speedy turnaround, I'm on v0.8.3-fc871e6f-win-x64 now and "h264 / amf" is back baby! All working!

**Comment by jasongdove** [comment] 2023-12-02 22:43
Thanks for the confirmation, will cut a new release later today.

**Closed** 2023-12-03 01:03 UTC
Labels: bug
