### ISSUE TITLE
Error when playing H.265 file. Maybe HDR10 issue?

### ISSUE THREAD

**Issue by Moonbase59** [ErsatzTV/ErsatzTV#1463] opened 2023-10-06 12:56 UTC
While diagnosing https://github.com/ErsatzTV/ErsatzTV/issues/1461, I tried to deliberately search for H.265/HEVC videos in order to see what CPU load they generate, because my VAAPI can’t decode them in hardware, and @jsongdove said

> - I would also watch for source content that is encoded with HEVC/H265 since your GPU does not support decoding that content, it will always be done in software/CPU. It also doesn't support encoding HEVC, so it's a good decision to leave the video format in the ffmpeg profile set to `h264`.

_Originally posted by @jasongdove in https://github.com/ErsatzTV/ErsatzTV/issues/1461#issuecomment-1750394770_

Now I set up a collection with only H.265 videos and started playing it, I get this error:

![Kein Programm – Mozilla Firefox_003](https://user-images.githubusercontent.com/3706922/273213516-853a74af-0e62-486d-846f-78a284bcbc11.png)

The video in question shows up in `xmltv.xml` as this:

```xml
<programme start="20231006133209 +0200" stop="20231006153628 +0200" channel="1.etv">
<title lang="en">Enola Holmes</title>
<desc lang="en">
Auf der Suche nach ihrer Mutter verlässt sich Enola Holmes auf ihr Talent als Spürnase, um ihren Bruder Sherlock zu überlisten und einem entlaufenen Lord zu helfen.
</desc>
<date>2020</date>
<category lang="en">Movie</category>
<category lang="en">Abenteuer</category>
<category lang="en">Komödie</category>
<category lang="en">Krimi</category>
<category lang="en">Mystery</category>
<icon src="http://media:8409/iptv/artwork/posters/jellyfin/Items/b4996061a4da74d847d91ea01d7f06c1/Images/Primary?tag=4f2089e703ac51855cb48c94ab4e2cee&fillHeight=440"/>
<previously-shown/>
<rating>
<value>FSK-12</value>
</rating>
</programme>
```

When I try to play it using mpv, VLC, Celluloid, KODI or Jellyfin, it plays just fine.

Here is the Mediainfo on the file:

```
General
Unique ID                                : 232077645815826606028474032697654849743 (0xAE98875C28480D5773E6E09ABB5330CF)
Complete name                            : /home/matthias/Videos/Movies/Enola Holmes (2020).mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 5.08 GiB
Duration                                 : 2 h 4 min
Overall bit rate                         : 5 850 kb/s
Movie name                               : Enola Holmes (2020)
Encoded date                             : UTC 2022-12-25 06:23:57
Writing application                      : mkvmerge v72.0.0 ('Minuano (Six-eight)') 64-bit
Writing library                          : libebml v1.4.4 + libmatroska v1.7.1

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L4@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.03, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 2 min
Bit rate                                 : 4 502 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.090
Stream size                              : 3.85 GiB (76%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1043 cd/m2
Maximum Frame-Average Light Level        : 196 cd/m2

Audio #1
ID                                       : 2
Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos
Codec ID                                 : A_EAC3
Duration                                 : 2 h 4 min
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 683 MiB (13%)
Title                                    : English DD+ Atmos 5.1
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No
Complexity index                         : 16
Number of dynamic objects                : 15
Bed channel count                        : 1 channel
Bed channel configuration                : LFE

Audio #2
ID                                       : 3
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 2 h 4 min
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 569 MiB (11%)
Title                                    : Deutsch DD+ 5.1
Language                                 : German
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Text #1
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 56 min
Bit rate                                 : 93 b/s
Count of elements                        : 2067
Stream size                              : 80.0 KiB (0%)
Title                                    : English SDH
Language                                 : English
Default                                  : No
Forced                                   : No

Text #2
ID                                       : 5
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2 h 1 min
Bit rate                                 : 50 b/s
Count of elements                        : 1569
Stream size                              : 45.0 KiB (0%)
Title                                    : Deutsch
Language                                 : German
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 6
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2 h 1 min
Bit rate                                 : 1 b/s
Count of elements                        : 50
Stream size                              : 1.15 KiB (0%)
Title                                    : Deutsch forced
Language                                 : German
Default                                  : No
Forced                                   : Yes

Text #4
ID                                       : 7
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2 h 1 min
Bit rate                                 : 51 b/s
Count of elements                        : 1515
Stream size                              : 46.3 KiB (0%)
Title                                    : Danish
Language                                 : Danish
Default                                  : No
Forced                                   : No

Text #5
ID                                       : 8
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2 h 1 min
Bit rate                                 : 50 b/s
Count of elements                        : 1578
Stream size                              : 45.3 KiB (0%)
Title                                    : French
Language                                 : French
Default                                  : No
Forced                                   : No

Text #6
ID                                       : 9
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2 h 1 min
Bit rate                                 : 50 b/s
Count of elements                        : 1545
Stream size                              : 45.2 KiB (0%)
Title                                    : Spanish
Language                                 : Spanish
Default                                  : No
Forced                                   : No

Text #7
ID                                       : 10
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2 h 1 min
Bit rate                                 : 82 b/s
Count of elements                        : 1564
Stream size                              : 73.4 KiB (0%)
Title                                    : Ukrainian
Language                                 : Ukrainian
Default                                  : No
Forced                                   : No
```

I suspect ETV can’t play HDR10 files? But I cannot safely exclude these from collections in a library with thousands of videos…

**EDIT:** Yes I can, by using a search like

```
video_codec:hevc AND type:movie AND video_bit_depth:8
```

But that only leaves 4 out of my 15 HEVC-encoded movies… and I would really like to schedule the other 11, too…

**Comment by jasongdove** [comment] 2023-10-06 13:24
The result will probably be similar, but note that bit depth and dynamic range are different. Try something like

```
video_codec:hevc AND type:movie AND video_dynamic_range:sdr
```

Closing this as a duplicate of #1297

**Closed by jasongdove** 2023-10-06 13:24 UTC

**Comment by Moonbase59** [comment] 2023-10-06 13:28
Ah, okay, so not supported yet. Thanks for the feedback, will try your suggested search.

And thanks for making the search so versatile!

**Comment by Moonbase59** [comment] 2023-10-06 13:35
Your search suggestion left 11 out of 15 movies, and they play fine, using ~17% of 6 CPUs, while H.264 sources only use ~3%.

So this is actually feasible, even if one doesn’t have H.265 hardware decoding/encoding.

Thanks again for helping—this is really some impressive piece of software!
